language: perl
perl:
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "cpanm --notest Dist::Zilla"
install: "dzil authordeps | xargs cpanm --notest && dzil listdeps | xargs cpanm --notest"
script: "dzil test --release"
